INSERT INTO team (name, tla, stadium, website, founded) VALUES
('Real Madrid CF', 'RMA', 'Santiago Bernabéu', 'https://www.realmadrid.com', 1902),
('FC Barcelona', 'BAR', 'Camp Nou', 'https://www.fcbarcelona.com', 1899),
('Atlético de Madrid', 'ATM', 'Wanda Metropolitano', 'https://www.atleticodemadrid.com', 1903),
('Real Sociedad', 'RSO', 'Anoeta (Reale Arena)', 'https://www.realsociedad.eus', 1909),
('Sevilla FC', 'SEV', 'Ramón Sánchez Pizjuán', 'https://www.sevillafc.es', 1890),
('Athletic Club', 'ATH', 'San Mamés', 'https://www.athletic-club.eus', 1898),
('Real Betis Balompié', 'BET', 'Benito Villamarín', 'https://www.realbetisbalompie.es', 1907),
('Villarreal CF', 'VIL', 'Estadio de la Cerámica', 'https://www.villarrealcf.es', 1923),
('Valencia CF', 'VAL', 'Mestalla', 'https://www.valenciacf.com', 1919),
('RC Celta de Vigo', 'CEL', 'Abanca-Balaídos', 'https://www.rccelta.es', 1923),
('RCD Espanyol', 'ESP', 'RCDE Stadium', 'https://www.rcdespanyol.com', 1900),
('Getafe CF', 'GET', 'Coliseum Alfonso Pérez', 'https://www.getafecf.com', 1983),
('RCD Mallorca', 'MAL', 'Son Moix', 'https://www.rcdmallorca.es', 1916),
('Real Valladolid CF', 'VAL', 'José Zorrilla', 'https://www.realvalladolid.es', 1928),
('CA Osasuna', 'OSA', 'El Sadar', 'https://www.osasuna.es', 1920),
('Almería', 'ALM', 'Estadio de los Juegos Mediterráneos', 'https://www.udalmeria.es', 1989),
('Granada CF', 'GRA', 'Nuevo Los Cármenes', 'https://www.granadacf.es', 1931),
('Girona FC', 'GIR', 'Montilivi', 'https://www.gironafc.cat', 1930),
('Rayo Vallecano', 'RAY', 'Campo de Fútbol de Vallecas', 'https://www.rayovallecano.es', 1924),
('Elche CF', 'ELC', 'Estadio Manuel Martínez Valero', 'https://www.elchecf.es', 1923),
('Real Murcia', 'MUR', 'Nueva Condomina', 'https://www.realmurcia.es', 1919);